name: "HA FFServer"
description: "HA FFServer"
version: 1.0.1
slug: "ha_ffserver"
codenotary: dev@norskfjellgeit.no
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: homeassistant
image: docker.io/norskfjellgeit/rtsp2mjpeg:{arch}
panel_icon: mdi:camera
panel_title: FFServer UI
options:
  camera_url: ""
  camera_width: 1920
  camera_height: 1080
  camera_fps: 2
  camera_still_fps: 1
schema:
  camera_url: str
  camera_width: int
  camera_height: int
  camera_fps: int
  camera_still_fps: int
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: Webcam HTTP