name: "HA FFServer"
description: "HA FFServer"
version: "1.0.0"
slug: "ha_ffserver"
init: false
arch:
  - aarch64
  - amd64
  - armv7
panel_icon: mdi:camera
panel_title: FFServer UI
options:
  camera_url: ""
  camera_width: 1920
  camera_height: 1080
  camera_fps: 2
  camera_still_fps: 1
schema:
  camera_url: str
  camera_width: int
  camera_height: int
  camera_fps: int
  camera_still_fps: int
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: Webcam HTTP